language: minimal

dist: bionic

services:
  - docker

jobs:
  include:
    - stage: GCC Builder
      name: "ARM64-GCC-10"     
      script: 
        - docker build -f Dockerfile.gcc-10-aarch64 . -t thagoo/gcc-builder:latest
        - docker run -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} -e TELEGRAM_TOKEN=${TELEGRAM_TOKEN} thagoo/gcc-builder
    - script:
        - docker build -f Dockerfile.gcc-10-arm . -t thagoo/gcc-builder:latest
        - docker run -e GH_PERSONAL_TOKEN=${GH_PERSONAL_TOKEN} -e TELEGRAM_TOKEN=${TELEGRAM_TOKEN} thagoo/gcc-builder
      name: "ARM-GCC-10"   

